In [1]:
import pandas as pd

In [8]:
url = "https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2025-11.parquet"
df_old = pd.read_parquet(url).head(10)
df_old

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,7,2025-11-01 00:13:25,2025-11-01 00:13:25,1.0,1.68,1.0,N,43,186,1,14.9,0.00,0.5,1.50,0.00,1.0,22.15,2.5,0.00,0.75
1,2,2025-11-01 00:49:07,2025-11-01 01:01:22,1.0,2.28,1.0,N,142,237,1,14.2,1.00,0.5,4.99,0.00,1.0,24.94,2.5,0.00,0.75
2,1,2025-11-01 00:07:19,2025-11-01 00:20:41,0.0,2.70,1.0,N,163,238,1,15.6,4.25,0.5,4.27,0.00,1.0,25.62,2.5,0.00,0.75
3,2,2025-11-01 00:00:00,2025-11-01 01:01:03,3.0,12.87,1.0,N,138,261,1,66.7,6.00,0.5,0.00,6.94,1.0,86.14,2.5,1.75,0.75
4,1,2025-11-01 00:18:50,2025-11-01 00:49:32,0.0,8.40,1.0,N,138,37,2,39.4,7.75,0.5,0.00,0.00,1.0,48.65,0.0,1.75,0.00
5,2,2025-11-01 00:21:11,2025-11-01 00:31:39,1.0,0.85,1.0,N,90,100,2,10.7,1.00,0.5,0.00,0.00,1.0,16.45,2.5,0.00,0.75
6,2,2025-11-01 00:07:31,2025-11-01 00:25:44,1.0,3.01,1.0,N,142,170,1,19.1,1.00,0.5,1.00,0.00,1.0,25.85,2.5,0.00,0.75
7,2,2025-11-01 00:46:52,2025-11-01 01:38:55,3.0,3.82,1.0,N,237,144,1,42.2,1.00,0.5,9.59,0.00,1.0,57.54,2.5,0.00,0.75
8,2,2025-11-01 00:56:59,2025-11-01 01:02:05,1.0,0.89,1.0,N,162,161,2,7.2,1.00,0.5,0.00,0.00,1.0,12.95,2.5,0.00,0.75
9,2,2025-11-01 00:10:43,2025-11-01 00:39:25,3.0,2.28,1.0,N,234,162,1,24.0,1.00,0.5,8.93,0.00,1.0,38.68,2.5,0.00,0.75

In [9]:
df_old.dtypes

VendorID                          int32
tpep_pickup_datetime     datetime64[us]
tpep_dropoff_datetime    datetime64[us]
passenger_count                 float64
trip_distance                   float64
RatecodeID                      float64
store_and_fwd_flag                  str
PULocationID                      int32
DOLocationID                      int32
payment_type                      int64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
improvement_surcharge           float64
total_amount                    float64
congestion_surcharge            float64
Airport_fee                     float64
cbd_congestion_fee              float64
dtype: object

In [2]:
uurl = "https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2025-10.parquet"

In [3]:
df = pd.read_parquet(uurl)

In [4]:
print(df.shape)
df.head()

(49416, 21)

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
0,2,2025-10-01 00:21:47,2025-10-01 00:24:37,N,1.0,247,69,1.0,0.70,5.8,...,0.5,1.70,0.00,NaN,1.0,10.00,1.0,1.0,0.00,0.00
1,2,2025-10-01 00:14:03,2025-10-01 00:24:14,N,1.0,66,25,1.0,1.61,11.4,...,0.5,2.78,0.00,NaN,1.0,16.68,1.0,1.0,0.00,0.00
2,2,2025-10-01 00:16:44,2025-10-01 00:16:47,N,5.0,244,244,1.0,0.00,10.0,...,0.0,2.20,0.00,NaN,1.0,13.20,1.0,2.0,0.00,0.00
3,2,2025-10-01 00:07:36,2025-10-01 00:32:14,N,1.0,95,170,1.0,10.37,43.6,...,0.5,11.31,6.94,NaN,1.0,67.85,1.0,1.0,2.75,0.75
4,2,2025-09-30 21:10:29,2025-09-30 21:22:30,N,1.0,82,138,1.0,4.07,19.8,...,0.5,6.82,0.00,NaN,1.0,34.12,1.0,1.0,0.00,0.00

In [6]:
df.dtypes

VendorID                          int32
lpep_pickup_datetime     datetime64[us]
lpep_dropoff_datetime    datetime64[us]
store_and_fwd_flag                  str
RatecodeID                      float64
PULocationID                      int32
DOLocationID                      int32
passenger_count                 float64
trip_distance                   float64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
ehail_fee                       float64
improvement_surcharge           float64
total_amount                    float64
payment_type                    float64
trip_type                       float64
congestion_surcharge            float64
cbd_congestion_fee              float64
dtype: object

In [7]:
df.query('trip_distance > 5')

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
3,2,2025-10-01 00:07:36,2025-10-01 00:32:14,N,1.0,95,170,1.0,10.37,43.60,...,0.5,11.31,6.94,NaN,1.0,67.85,1.0,1.0,2.75,0.75
5,2,2025-09-30 21:49:46,2025-10-01 21:18:42,N,1.0,129,37,1.0,7.13,35.20,...,0.5,9.42,0.00,NaN,1.0,47.12,1.0,1.0,0.00,0.00
7,2,2025-10-01 00:07:08,2025-10-01 00:21:46,N,1.0,95,70,1.0,6.01,26.10,...,0.5,5.72,0.00,NaN,1.0,34.32,1.0,1.0,0.00,0.00
8,2,2025-10-01 00:36:08,2025-10-01 00:54:59,N,1.0,181,137,1.0,6.45,28.90,...,0.5,6.98,0.00,NaN,1.0,41.88,1.0,1.0,2.75,0.75
11,2,2025-09-30 23:56:56,2025-10-01 00:10:51,N,5.0,95,80,1.0,8.37,90.00,...,0.0,0.00,0.00,NaN,1.0,91.00,1.0,2.0,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49404,6,2025-10-31 23:11:25,2025-10-31 23:54:40,NaN,NaN,226,47,NaN,11.49,2.90,...,0.5,0.00,0.00,NaN,0.3,39.11,NaN,NaN,NaN,0.00
49405,6,2025-10-31 23:27:46,2025-10-31 23:59:23,NaN,NaN,179,47,NaN,6.29,2.90,...,0.5,0.00,6.94,NaN,0.3,25.18,NaN,NaN,NaN,0.00
49406,2,2025-10-31 23:20:00,2025-10-31 23:47:00,NaN,NaN,66,230,NaN,6.74,46.93,...,0.5,10.39,0.00,NaN,1.0,62.32,NaN,NaN,NaN,0.75
49411,6,2025-10-31 23:02:00,2025-11-01 00:28:33,NaN,NaN,241,61,NaN,20.09,2.90,...,0.5,0.00,6.94,NaN,0.3,63.84,NaN,NaN,NaN,0.00
49412,6,2025-10-31 23:51:34,2025-11-01 00:20:58,NaN,NaN,53,225,NaN,10.11,0.00,...,0.5,0.00,0.00,NaN,0.3,34.76,NaN,NaN,NaN,0.00